### PR TITLE
Added my Fedora COPR (experimental repo)

### PR DESCRIPTION
**Pull request by AloisMahdal**
Today I tried to make SPEC file for slop.

I created a .spec file for slop and set up my COPR for building.  Also I
wrote [a script][1] that can produce the spec file and trigger new build from
sources at GitHub (my fork, for now):

  [1]: https://github.com/AloisMahdal/slop-copr-build

For now my plan is to keep an eye on new releases and re-run the script
manually (the script needs python-copr, which is only available at
Fedora AFAIK).

Should you consider providing "official" spec file, feel free to re-use
mine.

### CODE REVIEW

**Comment by naelstrof** [comment]
That's great, if you wouldn't mind, could you create a pull request with the spec file? Anything for getting slop on other platforms.

**Comment by AloisMahdal** [comment]
> could you create a pull request with the spec file?

Well, I'd be happy to, but the thing is... that you can't just put a .spec file inside and let people build it.  SPEC file needs tarball (or URL to one) to build, and it needs to have set version correctly; otherwise you'll end up with many RPMs versioned 1.2.3 but built from entirely different commits.  (That is, even if you made sure that you increase the version manually.)

Solutions that I know of are (OK, there are probably more, but these are ones I have good idea about how they work):

 *  Have .spec template and build script(s) inside the repo that can generate correct
     spec + tarball.  Then people can invoke rpmbuild and unless they intentionally mess
    with the .spec, they will end up with properly versioned RPM.

    (Shameless plug.)  This is what my project [MKit][1] tries to do although I never tried
    to use it for anything else than simple deployments of non-arch-specific scripts and files.

  [1]: https://github.com/AloisMahdal/mkit

 *  Have .spec file elsewhere and a real human maintainer to take care of the versioning
    (and possibly distro-specific patches or extra steps.)

    This is basically what most distros (Debian, Fedora, RHEL) do. Something in that sense,
    but far, far less sophisticated, is what I did.

The advantage of the current solution is that it's relatively close to the way Fedora does it, so we could gradually make it more Fedora-compatible up to the point that I could copy the SPEC file to real Fedora.  I haven't done it with any package so far but I'd be more than happy to use slop as a learning project.  (I'm actually working in Red Hat so I'm in good position to get some assistance with that).

So what do you think?

**Comment by naelstrof** [comment]
I feel unqualified to manage something like that, I pretty much just use Arch Linux, and I'm a pretty poor maintainer.
You're free to experiment with slop as much as you want, I'm sure regardless what happens slop will reach most major distributions eventually.

**Comment by TheLastProject** [comment]
Hey,

I tried to use the COPR repo to try to install slop for Fedora 27, but only 25 and 26 are supported. I know this pull request has been closed a while ago, but this seems the best place to ask if that repo could get Fedora 27 support added. Thanks!

**Comment by AloisMahdal** [comment]
@TheLastProject Indeed this is good place. I just enabled F27 and rawhide and [rebuilt][1]; it should be available by now. (FTR, F26 failed for some reason but it's identical to the older one.)

  [1]: https://copr.fedorainfracloud.org/coprs/amahdal/slop/build/697389/

**Pull request merged**
