### PR TITLE
Add move feature

### PR DESCRIPTION
**Pull request by itsxaos**
I added the ability to move the selection by holding down the space bar, as suggested in https://github.com/naelstrof/slop/issues/12#issuecomment-483077349 [(it also works like this in Mac OS)](https://twitter.com/sulco/status/1202218689669599234)
There might be mistakes (I don't program often), but it builds and works fine for me :slightly_smiling_face:.

I also restructured slopstates.{cpp,hpp} because I was having difficulty understanding it. I'm still not sure about the compensation when the mouse is on the outermost pixels, so please look over `slop::SlopState::determineCompensation()` carefully.

This should probably solve #12

### CODE REVIEW

**Comment by naelstrof** [comment]
Oh wow nice, I'll check it out this weekend.

**Comment by phisch** [comment]
Functionality wise, it works really well:
ioXb

**Comment by itsxaos** [comment]
Did you get a chance to look it over?
If you want me to change something just let me know 🙂!

**Comment by naelstrof** [comment]
This is so cool! I finally got around to reviewing it. I love it!
I'm so sorry you had to read all that awful code I made haha. I brought your code up to spec and merged it with a couple other people's work.

I made the --nokeyboard option make it so it no longer reads the spacebar.
I also made the movement clip the selection if it goes off the x-display. I think I like it more that way, but let me know if you think that should be relegated to an option!

**Comment by itsxaos** [comment]
Awesome!! 🙂
It's already in the arch repos and it works great!

Something I noticed while using it on my laptop is that it runs into issues with some palm rejection mechanisms, when using a touchpad (in my case I can't move the cursor while holding down space). Obviously that's not on slop and probably won't even occur for most touchpad users, but it's interesting to note.
Maybe there could be an analog to the --nodrag option for moving, but I doubt it would get much use.

**Comment by naelstrof** [comment]
> Something I noticed while using it on my laptop is that it runs into issues with some palm rejection mechanisms, when using a touchpad (in my case I can't move the cursor while holding down space).

That's a good point. slop in general can use a full keybinding system-- Though that brings in the argument that it might be easier for users to just clone the repo and replace the one instance of XK_SPACE than learn whatever keybinding system I bake up.

They also can simply disable the palm rejection mechanisms :v

> It's already in the arch repos and it works great!

Thanks so much for the drag feature! It's super clever and fits neatly in with the other features of slop. My apologies for how messy and awful the code is. I wrote this so long ago.

**Pull request merged**
