### PR TITLE
Fix cmake

### PR DESCRIPTION
**Pull request by SoapGentoo**
**Modernise CMake**

* Use `GNUInstallDirs` as it allows changing
  of all dirs in a standardised, Kitware
  supported way. `LIB_SUFFIX` is not idiomatic
  and not supported by Kitware:

    http://kwwidgets.org/Bug/view.php?id=10287

* Use ISO C++11 over the GNU variant, as this
  makes cross-platform porting efforts easier
  to other compilers.
* Don't search for a C compiler, speeds up
  configure step.
* Use proper idiom to change `CMAKE_INSTALL_PREFIX`
  default:

    https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT.html

**Do not compress manpage**

* The manpage is tiny, and distributions will
  recompress the manpage into a different
  format anyhow.

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@naelstrof can you please merge this?

**Comment by naelstrof** [comment]
Looks good, thanks

**Comment by SoapGentoo** [comment]
@naelstrof could you please tag a new release (and bump the version in `CMakelists.txt`) so we can add a fresh working release in Gentoo? Thanks.

**Comment by naelstrof** [comment]
I'm away from home right now, I'll tag a release when I get to a computer. Thanks for the hard work!

**Pull request merged**
